name: CI Integration test - Reusable

on:
  workflow_call:
    inputs:
      version_name:
        type: string
        required: true
      version_toolchain:
        type: string
        required: true

env:
  CI: 1
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-run-integration:
    name: Build and run integration
    runs-on: [taiko-runner]
    timeout-minutes: 120

    env:
      TARGET: ${{ inputs.version_name }}
      CI: 1
      MOCK: 1
