name: CI - SP1

on:
  workflow_call:
  push:
  pull_request:

jobs:
  build-test-sp1:
    name: Build and test sp1
    uses: ./.github/workflows/ci-build-test-reusable.yml
    with:
      version_name: "sp1"
      version_toolchain: "nightly-2024-04-18"

  integration-test-sp1:
    name: Run integration tests on sp1
    uses: ./.github/workflows/ci-integration-reusable.yml
    with:
      version_name: "sp1"
      version_toolchain: "nightly-2024-04-17"
